theme: jekyll-theme-cayman
title: "Open Learning Paths"
logo:
markdown: GFM
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

              - name: generate-sitemap
                uses: cicirello/generate-sitemap@v1.10.0
            
